import argparse
from constants import *
parser = argparse.ArgumentParser(description="Keyword Search CLI")
subparsers = parser.add_subparsers(dest="command", help="Available commands")
bm25_search = subparsers.add_parser("bm25search")
bm25_search.add_argument("term", type=str)
bm25_tf_parser = subparsers.add_parser("bm25tf", help="returns the tf of a doc using bm25")
bm25_tf_parser.add_argument("doc_id", type=int)
bm25_tf_parser.add_argument("term", type=str)
bm25_tf_parser.add_argument("k1", type=float, nargs="?", default=BM25_K1)
bm25_tf_parser.add_argument("b", type=float, nargs="?", default=BM25_B)
bm25_idf_parser = subparsers.add_parser("bm25idf", help="parser for the bm25idf calculation")
bm25_idf_parser.add_argument("term", type=str)
tfidf = subparsers.add_parser("tfidf", help="return the tfidf of a term")
tfidf.add_argument("doc_id", type=int)
tfidf.add_argument("term", type=str)
subparsers.add_parser("build", help="build the inverted index")
idf_parser = subparsers.add_parser("idf", help="returns the inverted doc freq")
idf_parser.add_argument("term", type=str, help="term to check inverted doc freq of")
tf_parser = subparsers.add_parser("tf", help="term frequency of a token")
tf_parser.add_argument("doc_id", type=int, help="document id")
tf_parser.add_argument("term", type=str, help="token to check")
search_parser = subparsers.add_parser("search", help="Search movies using keywords")
search_parser.add_argument("query", type=str, help="Search query")
args = parser.parse_args()